spring:
  application:
    name: microservice-discovery-euerka
  profiles:
      active: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123

